### ISSUE TITLE
Using describe in browser ...

### ISSUE THREAD

**Issue by goessner** [Yuffster/describe#1]
Hello Michelle,

I very like your tiny `describe` testing module.

When I use it in browser, line 25 gives an error, since `require` is not defined. You should guard it by

``` javascript
if (isModule)
    require('string-color');
```

I inline coded the coloring as a proposal. So `describe`now does not depend on other modules.
See my [tests](https://github.com/goessner/v2/tree/master/tests) how I did it.

If you like I would start a pull request.

Thanx
..
Stefan

**Comment by Yuffster** [comment]
Thanks Stefan!  Glad you like the module!

If you could do me a favor and do a pull request, I'd be happy to pull it!

Just add brackets around the if statement; I think I'm using some oldschool JSLint config there. ;)

**Comment by goessner** [comment]
ok .. I will do a pull request ..
..
Stefan
