### ISSUE TITLE
Please document the license you are making this available under, e.g. in your package.json file.

### ISSUE THREAD

**Issue by adysart78** [Yuffster/describe#3]

**Comment by Yuffster** [comment]
MIT. :grin:

**Comment by Yuffster** [comment]
https://github.com/Yuffster/describe/commit/80251fbd0aed666a334f0a6ea4e43aca76006edc

**Comment by adysart78** [comment]
Thank you for the quick response!

**Comment by Yuffster** [comment]
Any time, thanks for the brief and clear feature request. :grinning:
