### ISSUE TITLE
Allow multiple expect in one test case

### ISSUE THREAD

**Issue by mdamien** [Yuffster/describe#4]
Is it fitting to add the possibility to have multiple expect in one test case ?

**Comment by Yuffster** [comment]
Sounds good, make a test for it and submit a PR.

**Comment by mdamien** [comment]
will do, nice lib by the way !

Gonna add:
- `this.expectTestToFail();`: to be able to test the failing tests (very hacky, should be able to run each "describe" thingie independly of the test runner, = remove singleton)
- `this.expectNumberOfExpects(n);`: to be able to tell the number of expected tests

**Comment by Yuffster** [comment]
Can't wait to see what you come up with! 👍

**Comment by Yuffster** [comment]
Try to do each in its own PR so we can look over them individually.

**Comment by Yuffster** [comment]
PRs accepted for this, closing.
